# Site settings
title: King County Metro Paratransit Group
email: Valentina Staneva<vms16@uw.edu>
description: "#DSSG2015 @uwescience"
baseurl: "http://DSSG-paratransit.github.io/blog"
url: "http://DSSG-paratransit.github.io/blog"
twitter_username: uwescience
github_username:  uwescience

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->
